# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: HiFINI-Auto-CheckIn

on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30

jobs:
  build:
    env:
      COOKIE: "bbs_sid=8o6rk2oagb88abk9g8jrgb4mf0; Hm_lvt_23819a3dd53d3be5031ca942c6cbaf25=1762436911; HMACCOUNT=25F9049004D86C0D; bbs_token=si0yaWEunuGlFnGo01sIMZw1Wzm1FJmGgp9KcDcvoaF_2B0im9srNmkwrH6NJC5Sa4GNZH4Qa88w4nI9q6NkzBRZb_2BbFs_3D; Hm_lpvt_23819a3dd53d3be5031ca942c6cbaf25=1762477668"
      SERVER_CHAN: "SCT301782T5pl5qKqGpBVSIpceSCjBQt47"
      DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
      WXWORK_WEBHOOK: ${{ secrets.WXWORK_WEBHOOK }}
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      GOTIFY_URL: ${{ secrets.GOTIFY_URL }}
      GOTIFY_APP_TOKEN: ${{ secrets.GOTIFY_APP_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mvn compile
          mvn -B exec:java \
          -Dexec.mainClass=cloud.ohiyou.Main \
          -Dexec.cleanupDaemonThreads=false

